---
# handlers file for LinuxHardening

- name: squash
  ansible.builtin.command: rmmod squashfs
  register: result
  failed_when:
    - result.rc == 2

- name: udf
  ansible.builtin.command: rmmod udf
  register: result
  failed_when:
    - result.rc == 2

- name: usb
  ansible.builtin.command: rmmod usb-storage
  register: result
  failed_when:
    - result.rc == 2

- name: cramfs
  ansible.builtin.command: rmmod cramfs
  register: result
  failed_when:
    - result.rc == 2

- name: sys
  ansible.builtin.command: |
    sysctl --system
    sysctl -w net.ipv6.route.flush=1
    sysctl -w net.ipv4.route.flush=1

- name: core
  ansible.builtin.command: systemctl daemon-reload

- name: ssh
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: chage
  ansible.builtin.command: chage --inactive 30 ec2-user

- name: rsys
  ansible.builtin.service:
    name: rsyslog
    state: restarted
    enabled: yes

- name: iptables
  community.general.iptables_state:
    state: saved
    path: /etc/sysconfig/iptables
  notify: rc

- name: rc
  ansible.builtin.lineinfile:
    path: /etc/rc.local
    line: "/usr/sbin/iptables-restore < /etc/sysconfig/iptables"
  notify: chmod

- name: chmod
  ansible.builtin.file:
    path: /etc/rc.d/rc.local
    owner: root
    group: root
    mode: '0744'

- name: rebootz
  ansible.builtin.reboot:
    reboot_timeout: 3600
