---
#CIS Benchmark Section 3 Firewall + Section 4 Auditing

- name: Ensure firewalld service is running #3.5.1.4
  ansible.builtin.service:
    name: firewalld
    enabled: yes
    state: started

- name: Ensure audisp is configured per Cyber Threat Operations #Ray Standard
  ansible.builtin.lineinfile:
    path: /etc/audisp/plugins.d/syslog.conf
    regex: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: '^active ='
      line: "active = yes"
    - regexp: '^path ='
      line: "args = LOG_INFO LOG_LOCAL6"
  notify: rsys

- name: Ensure rsyslog is configured to send logs to a remote log host #4.2.1.5
  ansible.builtin.lineinfile:
    path: /etc/rsyslog.conf
    line: "local6.info;auth,authpriv.info @@138.126.126.58" #dfw-syslog ip is used
  notify: rsys

- name: Ensure CIS is Happy #4.2.1.5
  ansible.builtin.lineinfile:
    path: /etc/rsyslog.conf
    line: "*.* @@"

- name: Find those rsyslog files #4.2.1.3 pre-req
  ansible.builtin.find:
    paths: /etc/rsyslog.d/
    patterns: '*.conf'
  register: rsyslog

- name: Ensure rsyslog.d/config files default file permissions configured # 4.2.1.3
  ansible.builtin.lineinfile:
    path: "{{ item.path }}"
    regex: '^$FileCreateMode'
    line: "$FileCreateMode 0640"
  with_items: "{{ rsyslog.files }}"

- name: Ensure rsyslog.conf default file permissions configured #4.2.1.3
  ansible.builtin.lineinfile:
    path: /etc/rsyslog.conf
    regex: '$FileCreateMode'
    line: "$FileCreateMode 0640"

- name: Ensure journald is configured to send logs to rsyslog # 4.2.2.1--3
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regex: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: '^ForwardToSyslog='
      line: "ForwardToSyslog=yes"
    - regexp: '^Compress='
      line: "Compress=yes"
    - regexp: '^Storage='
      line: "Storage=persistent"
