---
# Tasks for CIS Benchmark Section 1

- name: Ensure mounting of cramfs filesystems is disabled #1.1.1.1
  ansible.builtin.lineinfile:
    path: /etc/modprobe.d/cramfs.conf
    regexp: '^install cramfs'
    line: "install cramfs /bin/true"
    create: yes
  notify: cramfs

- name: Ensure mounting of squashfs filesystems is disabled #1.1.1.2
  ansible.builtin.lineinfile:
    path: /etc/modprobe.d/squashfs.conf
    regexp: '^install squashfs'
    line: "install squashfs /bin/true"
    create: yes
  notify: squash

- name: Ensure mounting of udf filesystems is disabled #1.1.1.3
  ansible.builtin.lineinfile:
    path: /etc/modprobe.d/udf.conf
    regexp: '^install udf'
    line: "install udf /bin/true"
    create: yes
  notify: udf

- name: Ensure USB Storage is disabled #1.1.24
  ansible.builtin.lineinfile:
    path: /etc/modprobe.d/usb_storage.conf
    regexp: '^install usb-storage'
    line: "install usb-storage /bin/true"
    create: yes
  notify: usb


- name: Ensure AIDE is installed and a few other things #1.3.1
  ansible.builtin.yum:
    name:
      - aide
      - firewalld
      - iptables
      - policycoreutils-python
    state: latest

- name: Ensure crontab exists for aide to check fs integrity #1.3.2
  ansible.builtin.lineinfile:
    path: /etc/crontab
    line: "0 5 * * * /usr/sbin/aide --check"

- name: Check if system is UEFI or BIOS #Pre-Req to 1.4.1
  ansible.builtin.stat:
    path: /sys/firmware/efi
  register: efi

- name: Check if /boot/efi/EFI/amzn/grub.cfg exists
  ansible.builtin.stat:
    path: /boot/efi/EFI/amzn/grub.cfg
  register: grub

- name: Ensure permissions on bootloader are configured #1.4.1
  ansible.builtin.file:
    path: /boot/grub2/grub.cfg
    mode: '0700'
    owner: root
    group: root
  when: not efi.stat.exists

- name: Ensure /boot/efi/EFI/amzn/grub.cfg is good too #1.4.1
  ansible.builtin.file:
    path: /boot/efi/EFI/amzn/grub.cfg
    mode: '0700'
    owner: root
    group: root
  when: grub.stat.exists

- name: Ensure coredumps is good in that security #1.5.1
  ansible.builtin.lineinfile:
    path: /etc/security/limits.conf
    regexp: '^\* hard core 0'
    line: "* hard core 0"

- name: Ensure coredump.conf restricts coredumps #1.5.1
  ansible.builtin.lineinfile:
    path: /etc/systemd/coredump.conf
    regexp: '^Storage='
    line: "Storage=none"
  notify: core

- name: Ensure SELinux is permissive #1.6.1.4
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/selinux
    regex: '^SELINUX='
    line: "SELINUX=permissive"
  notify: rebootz


- name: Ensure Banners are in place. #1.7.2
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - src: templates/issue.j2
      dest: /etc/issue
    - src: templates/issue.net.j2
      dest: /etc/issue.net
