---
# tasks file for LinuxHardening

- import_tasks: ray_hygiene.yml

- import_tasks: filesystem.yml

- import_tasks: sysctl.yml

- import_tasks: special_services.yml

- import_tasks: auditing_fw.yml

- import_tasks: users_env.yml

- import_tasks: ssh_pw.yml

- import_tasks: vulnerabilites.yml
