---
# tasks file for Raytheon Environment

    - name: Import Raytheon Cert Chain #Ray Environment Hygiene
      ansible.builtin.copy:
        src: files/RaytheonCertBundle.pem
        dest: /etc/pki/ca-trust/source/anchors
        owner: root
        group: root
        mode: '0644'
      register: copied

    - name: Update Extracted Chain #Ray Environment Hygiene
      ansible.builtin.command: update-ca-trust --extracted
      when: copied.changed

    - name: Set proxy variables in profile.d #Ray Environment Hygiene
      ansible.builtin.copy:
        src: files/proxy.sh
        dest: /etc/profile.d/proxy.sh
        owner: root
        group: root
        mode: '0644'
      register: copy
