---

    - name: Windows Server 2019 Windows Remote Management (WinRM) client must not use Basic authentication #Cat I
      ansible.windows.win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\WinRM\Client
        name: AllowBasic
        data: 0
        datatype: dword

    - name: Windows Server 2019 Windows Remote Management (WinRM) service must not use Basic authentication #Cat I
      ansible.windows.win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\WinRM\Service
        name: AllowBasic
        data: 0
        datatype: dword

    - name: Windows Server 2019 must disable the Windows Installer Always install with elevated privileges option #Cat I
      ansible.windows.win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\Installer
        name: AlwaysInstallElevated
        data: 0
        datatype: dword

    - name: Windows Server 2019 Autoplay must be turned off for non-volume devices #Cat I
      ansible.windows.win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\Explorer
        name: NoAutoplayfornonVolume
        data: 1
        datatype: dword

    - name: Windows Server 2019 default AutoRun behavior must be configured to prevent AutoRun commands #Cat I
      ansible.windows.win_regedit:
        path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer
        name: NoAutorun
        data: 1
        datatype: dword

    - name: Windows Server 2019 AutoPlay must be disabled for all drives #Cat I
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer
        name: NoDriveTypeAutoRun
        data: 255
        datatype: dword

    - name: Windows Server 2019 must not allow anonymous enumeration of shares #Cat I
      ansible.windows.win_regedit:
        path: HKLM:\System\CurrentControlSet\Control\Lsa
        name: RestrictAnonymous
        data: 1
        datatype: dword
                
    - name: Windows Server 2019 LAN Manager authentication level must be configured to send NTLMv2 response only and to refuse LM and NTLM #Cat I
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
        name: LmCompatibilityLevel
        data: 5
        datatype: dword
