---
# tasks file for 2019DISA

- name: Gather distribution info
  setup:
    gather_subset: distribution,!all,!min
  when:
    - ansible_distribution is not defined

- name: Check OS version and family
  assert:
    that:
      - ansible_os_family == 'Windows'
      - ansible_distribution | regex_search('(Microsoft Windows Server 2019)')
    success_msg: "{{ ansible_distribution }} {{ ansible_distribution_major_version }} is the detected operating system."
    fail_msg: "This role can only be run against Windows Server 2019 Editions. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."

- name: Cat I
  import_tasks: cat1.yaml
  tags: cat1

- name: Cat II
  import_tasks: cat2.yaml
  tags: cat2

- name: Cat III
  import_tasks: cat3.yaml
  tags: cat3

- name: Vulnerabilities
  import_tasks: rapid7.yaml
  tags: rapid7
