galaxy_info:
  author: Adalberto Sanchez
  description: Harden Windows Server 2019 according to DISA STIG Benchmark V2R1
  company: 

  license: license (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: 2.1
  galaxy_tags: [STIG,DISA,Windows,2019,Server,Harden,Hardening]
